import Head from "next/head";
import Image from "next/image";
import { Button, Container, Typography } from "@mui/material";
import { useAuthContext } from "@/firebase/auth";
import { KeyboardDoubleArrowDownRounded } from "@mui/icons-material";

export default function Home() {
  const { user }: any = useAuthContext();

  return (
    <>
      <Head>
        <title>Reverie Health Care</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className="align-center">
        <Image
          src="/o.png"
          alt="Reverie Health Care"
          width={400}
          height={290}
        />
        <Typography variant="h4" sx={{ mt: 10, ml: "20%", mr: "20%" }}>
          &#34;One{" "}
          <Typography
            variant="h4"
            component="span"
            sx={{
              textDecoration: "underline",
              fontWeight: "bold",
              color: "#90caf9",
            }}
          >
            Step
          </Typography>{" "}
          ahead to your healthy life&#34;
        </Typography>
        <Typography sx={{ mt: 5, ml: "20%", mr: "20%", fontSize: 14 }}>
          Innovative Smart Robot with a focus on the health sector.
        </Typography>
        <Button
          variant="contained"
          color="primary"
          sx={{ mt: 5, mb: 5, ml: "20%", mr: "20%" }}
          onClick={() =>
            window.open(
              "https://www.instagram.com/nusantarayouthfoundation/",
              "_blank"
            )
          }
        >
          Join Us
        </Button>
        {/* <KeyboardDoubleArrowDownRounded
          className="floating-icon"
          sx={{ fontSize: 30, mt: 10, color: "#90caf9" }}
        /> */}
      </Container>
    </>
  );
}
